import Link from "next/link";
import { ArrowUpRight, ClipboardCheck, TrendingUp, Warehouse, ListChecks } from "lucide-react";
import { canOperateStore, defaultCooperativeId, getContext, isFullOperations, isOperations } from "@/lib/auth";
import { loadCore, scoreFor } from "@/lib/data";
import { formatDate, formatScore, areas } from "@/lib/scoring";
import { Empty, PageHeading, Score, Status } from "@/components/ui";
import { conceptBand } from "@/lib/criteria";
import { StartNewMenu } from "@/components/app-navigation";
import { reportKindLabel } from "@/lib/report-kind";
import { focusedStoreId, selectedStoreId } from "@/lib/store-focus";

export default async function Overview({ searchParams }: { searchParams: Promise<{ coop?: string; round?: string; store?: string }> }) {
  const params = await searchParams;
  const ctx = await getContext();
  const { data: focusCandidates } = isOperations(ctx.memberships) ? await ctx.supabase.from("stores").select("id,cooperative_id,name,active").eq("active", true) : { data: [] };
  const savedFocus = await focusedStoreId(focusCandidates || [], ctx.memberships);
  const requestedFocus = params.store && params.store !== "all" ? params.store : params.store === "all" ? null : savedFocus;
  const focusStore = (focusCandidates || []).find((store) => store.id === requestedFocus && canOperateStore(ctx.memberships, store.cooperative_id, store.id));
  const cooperativeId = ctx.memberships.some((m) => m.cooperative_id === params.coop) ? params.coop! : focusStore?.cooperative_id || defaultCooperativeId(ctx.memberships)!;
  const operations = isOperations(ctx.memberships, cooperativeId);
  const canMonthly = ctx.memberships.some((m) => m.role === "store_manager" && m.cooperative_id === cooperativeId);
  const { stores, rounds, reports, versions, areas: assessments, actions } = await loadCore(ctx.supabase, cooperativeId);
  const focused = await focusedStoreId(stores, ctx.memberships);
  const selectedStore = operations ? stores.find((store) => store.id === selectedStoreId(params.store, focused, stores)) : undefined;
  if (selectedStore) {
    const storeReports = reports.filter((report) => report.store_id === selectedStore.id && !report.archived_at);
    const published = storeReports.filter((report) => report.current_version_id && !report.withdrawn_at);
    const drafts = storeReports.flatMap((report) => versions.filter((version) => version.report_id === report.id && version.state === "draft").map((version) => ({ report, version })));
    const openActions = actions.filter((action) => action.status !== "done" && storeReports.some((report) => report.id === action.report_id));
    const latestConcept = published.find((report) => report.kind === "inspection");
    const latestMonthly = published.find((report) => report.kind === "self_check" && !report.event_id);
    return <><PageHeading eyebrow="Varehus i fokus" title={selectedStore.name} description="Pågående arbeid, rapporter og oppgaver for dette varehuset."><Link className="button" href={`/varehus/${selectedStore.id}`}>Varehusside</Link><StartNewMenu operations={operations} fullOperations={isFullOperations(ctx.memberships, cooperativeId)} monthly={canMonthly} storeId={selectedStore.id}/></PageHeading>
      <div className="grid-4"><div className="stat-card"><span className="label">Pågående rapporter</span><strong className="value">{drafts.length}</strong><Link className="panel-link" href={`/rapporter?view=active&store=${selectedStore.id}`}>Se kladder</Link></div><div className="stat-card"><span className="label">Siste konseptsjekk</span><strong className="value">{formatScore(scoreFor(latestConcept, versions, assessments))}</strong><span className="hint">{formatDate(versions.find((version) => version.id === latestConcept?.current_version_id)?.visit_date)}</span></div><div className="stat-card"><span className="label">Siste driftsgjennomgang</span><strong className="value">{formatScore(scoreFor(latestMonthly, versions, assessments))}</strong><span className="hint">Intern progresjon</span></div><div className="stat-card"><span className="label">Åpne oppgaver</span><strong className="value">{openActions.length}</strong><Link className="panel-link" href={`/oppfolging?store=${selectedStore.id}`}>Se oppgaver</Link></div></div>
      <div className="grid-2"><section className="panel"><div className="panel-header"><h2>Pågående</h2><Link className="panel-link" href={`/rapporter?view=active&store=${selectedStore.id}`}>Se alle</Link></div>{drafts.slice(0, 5).map(({report, version}) => <Link className="list-card" href={`/rapporter/rediger/${version.id}`} key={version.id}><div><h3>{reportKindLabel(report.kind, report.event_id)}</h3><p>Fortsett kladd · {formatDate(version.visit_date || report.created_at)}</p></div><ArrowUpRight size={18}/></Link>)}{!drafts.length && <p className="muted">Ingen pågående rapporter.</p>}</section><section className="panel"><div className="panel-header"><h2>Åpne oppgaver</h2><Link className="panel-link" href={`/oppfolging?store=${selectedStore.id}`}>Se alle</Link></div>{openActions.slice(0, 5).map((action) => <Link className="list-card" href={`/oppfolging/${action.id}`} key={action.id}><div><h3>{action.description}</h3><p>Frist {formatDate(action.due_date)}</p></div><Status value={action.status}/></Link>)}{!openActions.length && <p className="muted">Ingen åpne oppgaver.</p>}</section></div>
      <section className="panel"><div className="panel-header"><h2>Siste rapporter</h2><Link className="panel-link" href={`/rapporter?view=history&store=${selectedStore.id}`}>Se historikk</Link></div>{published.slice(0, 5).map((report) => <Link className="list-card" href={`/rapporter/${report.id}`} key={report.id}><div><h3>{reportKindLabel(report.kind, report.event_id)}</h3><p>{formatDate(versions.find((version) => version.id === report.current_version_id)?.visit_date)}</p></div><Score value={scoreFor(report, versions, assessments)} neutral={report.kind === "self_check"}/></Link>)}{!published.length && <p className="muted">Ingen publiserte rapporter.</p>}</section>
    </>;
  }
  const { data: upcomingEvents } = await ctx.supabase.from("events").select("id,title,starts_at,location_store_id").eq("status","planned").order("starts_at",{ascending:true}).limit(3);
  const { data: cooperatives } = await ctx.supabase.from("cooperatives").select("id,name");
  const currentRound = rounds.find((r) => r.id === params.round) || rounds[0];
  const roundReports = reports.filter((r) => r.kind === "inspection" && r.round_id === currentRound?.id && r.current_version_id && !r.withdrawn_at);
  const ranking = roundReports.map((r) => ({ report: r, store: stores.find((s) => s.id === r.store_id), version: versions.find((v) => v.id === r.current_version_id), score: scoreFor(r, versions, assessments) })).sort((a,b) => (b.score || 0) - (a.score || 0));
  const { data: participants } = currentRound ? await ctx.supabase.from("round_stores").select("store_id,exception_reason").eq("round_id", currentRound.id) : { data: [] };
  const expected = (participants || []).filter((p) => !p.exception_reason).length;
  const completion = expected ? Math.round(ranking.length / expected * 100) : 0;
  const average = ranking.length ? ranking.reduce((sum,r) => sum + (r.score || 0), 0) / ranking.length : null;
  const activeActions = actions.filter((a) => a.status !== "done");
  const myStoreIds = ctx.memberships.filter((m) => m.role === "store_manager" && m.cooperative_id === cooperativeId).map((m) => m.store_id);
  const ownReports = reports.filter((r) => myStoreIds.includes(r.store_id) && r.current_version_id && !r.withdrawn_at);
  return <><PageHeading eyebrow="Oversikt" title={`God dag, ${ctx.name.split(" ")[0]}`} description={operations ? "Status, utvikling og prioriteringer på ett sted." : "Her ser du vurderinger og oppfølging for ditt varehus."}><StartNewMenu operations={operations} fullOperations={isFullOperations(ctx.memberships,cooperativeId)} monthly={canMonthly}/></PageHeading>
    {upcomingEvents && upcomingEvents.length > 0 && <section className="panel" style={{marginTop:0,marginBottom:20}}><div className="panel-header"><h2>Samlinger og konseptrunder</h2><Link className="panel-link" href="/samlinger">Se alle</Link></div>{upcomingEvents.map((event)=><Link className="list-card" href={`/samlinger/${event.id}`} key={event.id}><div><h3>{event.title}</h3><p>{new Intl.DateTimeFormat("nb-NO",{timeZone:"Europe/Oslo",dateStyle:"medium",timeStyle:"short"}).format(new Date(event.starts_at))} · {stores.find((store)=>store.id===event.location_store_id)?.name||"Varehus"}</p></div><ArrowUpRight size={17}/></Link>)}</section>}
    {operations && <form className="filters overview-filters no-print"><label className="filter-field" htmlFor="coop">Samvirkelag<select id="coop" name="coop" defaultValue={cooperativeId}>{[...new Set(ctx.memberships.filter((m) => m.role === "operations").map((m) => m.cooperative_id))].map((id) => <option key={id} value={id}>{cooperatives?.find((c) => c.id === id)?.name || "Samvirkelag"}</option>)}</select></label><label className="filter-field" htmlFor="round">Runde<select id="round" name="round" defaultValue={currentRound?.id}>{rounds.map((r) => <option key={r.id} value={r.id}>{r.title}</option>)}</select></label><button className="button">Vis</button></form>}
    {operations ? <><div className="grid-4" style={{marginTop:20}}><div className="stat-card"><span className="stat-icon"><TrendingUp size={19}/></span><span className="label">Rundens snitt</span><strong className="value">{formatScore(average)}</strong><span className="hint">{currentRound ? currentRound.title : "Ingen runde valgt"}</span></div><div className="stat-card"><span className="stat-icon"><ClipboardCheck size={19}/></span><span className="label">Gjennomføringsgrad</span><strong className="value">{completion} %</strong><span className="hint">{ranking.length} av {expected} forventede varehus</span></div><div className="stat-card"><span className="stat-icon"><Warehouse size={19}/></span><span className="label">Høyest vurdert</span><strong className="value" style={{fontSize:"1.28rem",marginTop:12}}>{ranking[0]?.store?.name || "—"}</strong><span className="hint">{ranking[0] ? `${formatScore(ranking[0].score)} poeng` : "Ingen publiserte vurderinger"}</span></div><div className="stat-card"><span className="stat-icon"><ListChecks size={19}/></span><span className="label">Åpne tiltak</span><strong className="value">{activeActions.length}</strong><span className="hint">{activeActions.filter((a) => a.due_date && a.due_date < new Date().toISOString().slice(0,10)).length} forfalt</span></div></div>
    <section className="panel"><div className="panel-header"><div><h2>Rangering i runden</h2><p className="muted small" style={{margin:"5px 0 0"}}>{currentRound?.status !== "closed" ? `Foreløpig – ${ranking.length} av ${expected} varehus vurdert` : "Avsluttet runde"}</p></div><Link className="panel-link" href="/runder">Se runder <ArrowUpRight size={14}/></Link></div>{ranking.length ? <div className="table-wrap"><table><thead><tr><th>Plass</th><th>Varehus</th><th>Total</th>{areas.map((a) => <th key={a.key}>{a.label}</th>)}<th>Besøksdato</th></tr></thead><tbody>{ranking.map((row) => <tr key={row.report.id}><td className="rank">{ranking.findIndex((item) => item.score === row.score) + 1}</td><td><Link href={`/rapporter/${row.report.id}`}>{row.store?.name}</Link></td><td><Score value={row.score}/></td>{areas.map((area) => { const score = assessments.find((a) => a.version_id === row.version?.id && a.area_key === area.key)?.score_quarters; return <td key={area.key}><span className={`heat-cell ${conceptBand(score == null ? null : score / 4)}`}>{formatScore(score == null ? null : score / 4)}</span></td>; })}<td>{formatDate(row.version?.visit_date)}</td></tr>)}</tbody></table></div> : <Empty title="Ingen publiserte vurderinger i runden" description="Opprett en konseptsjekk for å starte rangeringen." href="/rapporter/ny?type=inspection" action="Ny konseptsjekk"/>}</section>
    <div className="grid-2"><section className="panel"><div className="panel-header"><h2>Gjenstår i runden</h2></div>{(participants || []).filter((p) => !p.exception_reason && !roundReports.some((r) => r.store_id === p.store_id)).slice(0,6).map((p) => <div className="list-card" key={p.store_id}><div><h3>{stores.find((s) => s.id === p.store_id)?.name}</h3><p>Ingen publisert konseptsjekk</p></div><Status value="planned"/></div>)}{!participants?.length && <p className="muted">Ingen runde valgt.</p>}</section><section className="panel"><div className="panel-header"><h2>Åpne tiltak</h2><Link className="panel-link" href="/oppfolging">Se alle</Link></div>{activeActions.slice(0,5).map((a) => <div className="list-card" key={a.id}><div><h3>{a.description}</h3><p>{stores.find((s) => s.id === reports.find((r) => r.id === a.report_id)?.store_id)?.name} · Frist {formatDate(a.due_date)}</p></div><Status value={a.status}/></div>)}{!activeActions.length && <p className="muted">Ingen åpne tiltak.</p>}</section></div></> : <><div className="grid-4"><div className="stat-card"><span className="label">Siste konseptsjekk</span><strong className="value">{formatScore(scoreFor(ownReports.find((r) => r.kind === "inspection"),versions,assessments))}</strong><span className="hint">Offisiell vurdering</span></div><div className="stat-card"><span className="label">Driftsgjennomganger</span><strong className="value">{formatScore(scoreFor(ownReports.find((r) => r.kind === "self_check" && !r.event_id),versions,assessments))}</strong><span className="hint">Siste driftskarakter · {ownReports.filter((r) => r.kind === "self_check" && !r.event_id).length} gjennomganger</span></div><div className="stat-card"><span className="label">Åpne tiltak</span><strong className="value">{activeActions.length}</strong></div><div className="stat-card"><span className="label">Varehus</span><strong className="value" style={{fontSize:"1.3rem"}}>{stores.find((s) => myStoreIds.includes(s.id))?.name || "—"}</strong></div></div><section className="panel"><div className="panel-header"><h2>Siste rapporter</h2><Link className="panel-link" href="/rapporter">Se arkiv</Link></div>{ownReports.slice(0,5).map((r) => <div className="list-card" key={r.id}><div><h3><Link href={`/rapporter/${r.id}`}>{reportKindLabel(r.kind,r.event_id)}</Link></h3><p>{formatDate(versions.find((v) => v.id === r.current_version_id)?.visit_date)}</p></div><Score value={scoreFor(r,versions,assessments)} neutral={r.kind === "self_check"}/></div>)}{!ownReports.length && <Empty title="Ingen publiserte rapporter ennå"/>}</section></>}
  </>;
}
