"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Coop={id:string;name:string};type Store={id:string;name:string;cooperative_id:string;active:boolean};type Membership={id:string;user_id:string;cooperative_id:string;store_id:string|null;role:string};type Profile={id:string;display_name:string};
export default function AdminControls({coops,stores,memberships,profiles}:{coops:Coop[];stores:Store[];memberships:Membership[];profiles:Profile[]}){const router=useRouter();const [coop,setCoop]=useState(coops[0]?.id||"");const [name,setName]=useState("");const [email,setEmail]=useState("");const [person,setPerson]=useState("");const [role,setRole]=useState("store_manager");const [storeId,setStoreId]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  async function createStore(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/stores",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cooperativeId:coop,name})});const result=await response.json();setMessage(response.ok?"Varehuset er opprettet.":result.error||"Feil");setBusy(false);if(response.ok){setName("");router.refresh();}}
  async function invite(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cooperativeId:coop,storeId:role==="store_manager"?storeId:null,role,email,name:person})});const result=await response.json();setMessage(response.ok?"Invitasjon sendt og rolle tildelt.":result.error||"Invitasjon feilet");setBusy(false);if(response.ok){setEmail("");setPerson("");router.refresh();}}
  async function revoke(id:string){if(!confirm("Fjerne denne tilgangen?"))return;const response=await fetch(`/api/memberships/${id}`,{method:"DELETE"});const result=await response.json();setMessage(response.ok?"Tilgangen er fjernet.":result.error||"Kunne ikke fjerne tilgang");if(response.ok)router.refresh();}
  return <><div className="filters" style={{marginBottom:20}}><label>Samvirkelag <select value={coop} onChange={(e)=>{setCoop(e.target.value);setStoreId("");}}>{coops.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="grid-2"><section className="panel" style={{marginTop:0}}><h2>Legg til varehus</h2><form className="form-stack" onSubmit={createStore}><label>Varehusnavn<input value={name} onChange={(e)=>setName(e.target.value)} required minLength={2}/></label><button className="button primary" disabled={busy}>Opprett varehus</button></form></section><section className="panel" style={{marginTop:0}}><h2>Inviter bruker</h2><form className="form-stack" onSubmit={invite}><label>Navn<input value={person} onChange={(e)=>setPerson(e.target.value)} required minLength={2}/></label><label>E-post<input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></label><label>Rolle<select value={role} onChange={(e)=>setRole(e.target.value)}><option value="store_manager">Varehussjef</option><option value="operations">Driftssjef</option><option value="cooperative_admin">Samvirkelagsadministrator</option></select></label>{role==="store_manager"&&<label>Varehus<select required value={storeId} onChange={(e)=>setStoreId(e.target.value)}><option value="">Velg varehus</option>{stores.filter((s)=>s.cooperative_id===coop&&s.active).map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button className="button primary" disabled={busy}>Send invitasjon</button></form></section></div>{message&&<p role="status" className="feedback">{message}</p>}<section className="panel"><h2>Rolletildelinger</h2><div className="table-wrap"><table><thead><tr><th>Bruker</th><th>Rolle</th><th>Varehus</th><th></th></tr></thead><tbody>{memberships.filter((m)=>m.cooperative_id===coop).map((m)=><tr key={m.id}><td>{profiles.find((p)=>p.id===m.user_id)?.display_name||m.user_id.slice(0,8)}</td><td>{m.role==="operations"?"Driftssjef":m.role==="store_manager"?"Varehussjef":"Administrator"}</td><td>{stores.find((s)=>s.id===m.store_id)?.name||"Alle i samvirkelaget"}</td><td><button className="text-button" onClick={()=>void revoke(m.id)}>Fjern tilgang</button></td></tr>)}</tbody></table></div></section></>}
