import Link from "next/link";
import { getContext, isOperations } from "@/lib/auth";
import { loadCore, scoreFor } from "@/lib/data";
import { formatDate } from "@/lib/scoring";
import { Empty, PageHeading, Score, Status } from "@/components/ui";
import { StartNewMenu } from "@/components/app-navigation";

export default async function Reports({ searchParams }: { searchParams: Promise<{ store?:string; kind?:string; year?:string; page?:string }> }) {
  const params=await searchParams; const ctx=await getContext(); const data=await loadCore(ctx.supabase);
  const page=Math.max(1,Number(params.page)||1); const pageSize=20;
  const filtered=data.reports.filter((r) => !r.archived_at && (!params.store || r.store_id===params.store) && (!params.kind || r.kind===params.kind))
    .filter((r) => !params.year || data.versions.find((v) => v.id===r.current_version_id)?.visit_date?.startsWith(params.year));
  const visible=filtered.slice((page-1)*pageSize,page*pageSize);
  return <><PageHeading eyebrow="Arkiv" title="Rapporter" description="Se publiserte vurderinger og kladder du har tilgang til."><Link className="button" href="/rapporter/utvikling">Utviklingsrapport</Link><StartNewMenu operations={isOperations(ctx.memberships)} monthly={ctx.memberships.some((m)=>m.role==="store_manager")}/></PageHeading><form className="filters" style={{marginBottom:20}}><select name="store" defaultValue={params.store||""} aria-label="Filtrer varehus"><option value="">Alle varehus</option>{data.stores.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="kind" defaultValue={params.kind||""} aria-label="Filtrer rapporttype"><option value="">Alle typer</option><option value="inspection">Uanmeldt konseptsjekk</option><option value="self_check">Månedlig driftsgjennomgang</option></select><input name="year" type="number" min="2000" max="2100" placeholder="År" defaultValue={params.year||""} aria-label="År"/><button className="button">Filtrer</button></form><section className="panel"><div className="panel-header"><h2>{filtered.length} rapporter</h2><span className="muted small">Side {page}</span></div>{visible.length?<div className="table-wrap"><table><thead><tr><th>Varehus</th><th>Type</th><th>Dato</th><th>Runde</th><th>Status</th><th>Karakter</th><th></th></tr></thead><tbody>{visible.map((r)=>{const v=data.versions.find((v)=>v.id===r.current_version_id);return <tr key={r.id}><td><Link href={`/rapporter/${r.id}`}>{data.stores.find((s)=>s.id===r.store_id)?.name}</Link></td><td>{r.kind==="inspection"?"Uanmeldt konseptsjekk":"Månedlig driftsgjennomgang"}</td><td>{formatDate(v?.visit_date)}</td><td>{data.rounds.find((round)=>round.id===r.round_id)?.title||"Enkeltbesøk"}</td><td><Status value={r.withdrawn_at?"withdrawn":v?"published":"draft"}/></td><td>{r.kind==="inspection"?<Score value={scoreFor(r,data.versions,data.areas)}/>:<span className="muted small">Ikke gjeldende</span>}</td><td><Link className="panel-link" href={v?`/rapporter/${r.id}`:`/rapporter/rediger/${data.versions.find((draft)=>draft.report_id===r.id&&draft.state==="draft")?.id}`}>Åpne</Link></td></tr>})}</tbody></table></div>:<Empty title="Ingen rapporter funnet" description="Juster filtrene eller opprett en ny rapport."/>}</section><div className="page-actions" style={{justifyContent:"flex-end",marginTop:15}}>{page>1&&<Link className="button" href={`?page=${page-1}&store=${params.store||""}&kind=${params.kind||""}&year=${params.year||""}`}>Forrige</Link>}{filtered.length>page*pageSize&&<Link className="button" href={`?page=${page+1}&store=${params.store||""}&kind=${params.kind||""}&year=${params.year||""}`}>Neste</Link>}</div></>;
}
