import type { Area, Report, Round, Store } from "@/lib/data";
import { compareRounds } from "@/lib/analytics";
import { areas as areaDefs, formatScore } from "@/lib/scoring";
export default function RoundComparison({roundId,compareId,rounds,reports,areas,stores}:{roundId:string;compareId?:string;rounds:Round[];reports:Report[];areas:Area[];stores:Store[]}){
  const currentRound=rounds.find((r)=>r.id===roundId);
  const alternatives=rounds.filter((r)=>r.sequence_no<(currentRound?.sequence_no??0));
  const previous=alternatives.find((r)=>r.id===compareId)||alternatives[0];
  const rows=(id:string)=>reports.filter((r)=>r.round_id===id&&r.current_version_id&&!r.withdrawn_at&&r.kind==="inspection").map((r)=>({storeId:r.store_id,totalQuartersSum:areas.filter((a)=>a.version_id===r.current_version_id).reduce((sum,a)=>sum+(a.score_quarters||0),0)})).filter((r)=>r.totalQuartersSum>=16);
  const result=compareRounds(rows(roundId),previous?rows(previous.id):[]);
  const areaAverage=(id:string,key:string)=>{const relevant=reports.filter((r)=>r.round_id===id&&r.current_version_id&&!r.withdrawn_at&&r.kind==="inspection");const values=relevant.map((r)=>areas.find((a)=>a.version_id===r.current_version_id&&a.area_key===key)?.score_quarters).filter((n):n is number=>typeof n==="number");return values.length?values.reduce((a,b)=>a+b,0)/(values.length*4):null;};
  const best=result.changes.find((c)=>c.change>0);const worst=[...result.changes].reverse().find((c)=>c.change<0);
  return <section className="panel"><div className="panel-header"><h2>Sammenligning med tidligere runde</h2></div>{alternatives.length?<><form className="filters"><select name="compare" defaultValue={previous?.id} aria-label="Sammenligningsrunde">{alternatives.map((r)=><option key={r.id} value={r.id}>{r.title}</option>)}</select><button className="button">Sammenlign</button></form><div className="grid-4" style={{marginTop:20}}><div><p className="muted small">Valgt rundes faktiske snitt</p><strong style={{fontSize:24}}>{formatScore(result.currentAverage)}</strong></div><div><p className="muted small">Tidligere rundes faktiske snitt</p><strong style={{fontSize:24}}>{formatScore(result.previousAverage)}</strong></div><div><p className="muted small">Endring i felles utvalg</p><strong style={{fontSize:24}}>{result.commonChange===null?"Ingen sammenligning":`${result.commonChange>=0?"+":""}${formatScore(result.commonChange)} poeng`}</strong></div><div><p className="muted small">Felles utvalg</p><strong style={{fontSize:24}}>{result.commonCount} varehus</strong></div></div><div className="grid-2" style={{marginTop:18}}><div><p className="muted small">Størst forbedring</p><strong>{best?`${stores.find((s)=>s.id===best.storeId)?.name||"Varehus"} · +${formatScore(best.change)} poeng`:"Ingen sammenligning"}</strong></div><div><p className="muted small">Størst tilbakegang</p><strong>{worst?`${stores.find((s)=>s.id===worst.storeId)?.name||"Varehus"} · ${formatScore(worst.change)} poeng`:"Ingen sammenligning"}</strong></div></div><h3 style={{marginTop:28}}>Områdesnitt</h3><div className="table-wrap"><table><thead><tr><th>Område</th><th>Valgt runde</th><th>Tidligere runde</th></tr></thead><tbody>{areaDefs.map((area)=>{const current=areaAverage(roundId,area.key);const old=previous?areaAverage(previous.id,area.key):null;return <tr key={area.key}><td>{area.label}</td><td><strong>{formatScore(current)}</strong><div className="progress-track" style={{maxWidth:180}}><div className="progress-fill" style={{width:`${current?current*10:0}%`}}/></div></td><td><strong>{formatScore(old)}</strong><div className="progress-track" style={{maxWidth:180}}><div className="progress-fill" style={{width:`${old?old*10:0}%`,background:"var(--navy-2)"}}/></div></td></tr>})}</tbody></table></div><p className="muted small" style={{marginTop:20,marginBottom:0}}>Endringen er beregnet kun for varehus med publisert konseptsjekk i begge runder. De to faktiske rundesnittene kan ha ulik deltakersammensetning.</p></>:<p className="muted">Ingen tidligere runde å sammenligne med.</p>}</section>;
}
