"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Store={id:string;name:string;cooperative_id:string}; type Coop={id:string;name:string};
export default function NewRoundForm({stores,coops}:{stores:Store[];coops:Coop[]}){
  const router=useRouter();const [coop,setCoop]=useState(coops[0]?.id||"");const [title,setTitle]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [selected,setSelected]=useState<string[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const available=stores.filter((s)=>s.cooperative_id===coop);
  async function submit(event:React.FormEvent){event.preventDefault();setError("");setBusy(true);const response=await fetch("/api/rounds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cooperativeId:coop,title,from:from||null,to:to||null,storeIds:selected})});const result=await response.json();if(!response.ok){setError(result.error||"Kunne ikke opprette runden");setBusy(false);return;}router.push(`/runder/${result.roundId}`);}
  return <form className="form-stack" onSubmit={submit}><label>Samvirkelag<select value={coop} onChange={(e)=>{setCoop(e.target.value);setSelected([]);}}>{coops.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Navn på runden<input required maxLength={150} value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Driftsrunde 1 – vår 2027"/></label><div className="grid-2"><label>Planlagt fra<input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/></label><label>Planlagt til<input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></label></div><fieldset style={{border:"1px solid var(--line)",borderRadius:9,padding:17}}><legend style={{fontWeight:750}}>Varehus i runden</legend>{available.map((s)=><label key={s.id} style={{display:"flex",gap:8,alignItems:"center",padding:"7px 0"}}><input type="checkbox" checked={selected.includes(s.id)} onChange={(e)=>setSelected((old)=>e.target.checked?[...old,s.id]:old.filter((id)=>id!==s.id))}/>{s.name}</label>)}{!available.length&&<p className="muted">Ingen aktive varehus.</p>}</fieldset>{error&&<p role="alert" className="feedback error">{error}</p>}<button className="button primary" disabled={busy||!selected.length}>{busy?"Oppretter …":"Opprett runde"}</button></form>;
}
